# fly.toml app configuration file generated for nicegui on 2023-10-05T05:09:32+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nicegui"
primary_region = "fra"
kill_signal = "SIGTERM"
kill_timeout = "5s"

[build]
  dockerfile = "fly.dockerfile"

[deploy]
  strategy = "canary"

[processes]
  app = ""

[env]
  SWAP = "true"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 10

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 200
    soft_limit = 100

  [[services.tcp_checks]]
    interval = "10s"
    timeout = "5s"
    grace_period = "30s"

  [[services.http_checks]]
    interval = "20s"
    timeout = "10s"
    grace_period = "1m0s"
    method = "get"
    path = "/status"
    protocol = "http"
    tls_skip_verify = false

[[metrics]]
  path = "/"
  port = 9062
