blank_issues_enabled: false
contact_links:
  - name: Report a Security Vulnerability
    url: https://github.com/zauberzeug/nicegui?tab=security-ov-file#readme
    about: Please review our security policy for more details.
  - name: Have an idea or a feature requests?
    url: https://github.com/zauberzeug/nicegui/discussions/categories/ideas-feature-requests
    about: Visit the "ğŸ’¡ Ideas / Feature Requests" forum to view, discuss, vote and propose ideas and feature suggestions.
  - name: Need support from the developers?
    url: https://github.com/zauberzeug/nicegui/discussions/categories/q-a
    about: Visit the "ğŸ™ Q&A" forum to find answers or to ask new questions to the developers.
  - name: Ask on Discord
    url: https://discord.gg/TEpFeAaF4f
    about: Get in touch with the NiceGUI community, get support and have a chat about your project.
  - name: Ask on StackOverflow
    url: https://stackoverflow.com/questions/tagged/nicegui
    about: Get help from a larger community by asking on StackOverflow.
