name: Slack Notification

on:
  workflow_call:
    inputs:
      workflow-name:
        description: "Name for Slack notifications"
        required: true
        type: string

jobs:
  slack:
    if: always() # also execute when tests fail
    runs-on: ubuntu-latest
    steps:
      - uses: Jimdo/should-i-notify-action@main
        id: should_notify
        with:
          needs_context: ${{ toJson(needs) }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check if secret exists
        id: check_secret
        run: echo "exists=${{ secrets.SLACK_ROBOTICS_CI_WEBHOOK != '' }}" >> $GITHUB_OUTPUT
      - uses: Gamesight/slack-workflow-status@master
        if: steps.should_notify.outputs.should_send_message == 'yes' && steps.check_secret.outputs.exists == 'true'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_ROBOTICS_CI_WEBHOOK }}
          channel: "robotik-ci"
          name: ${{ inputs.workflow-name }}
