name: Release on Zenodo

on:
  release:
    types: [published]

jobs:
  upload-to-zenodo:
    runs-on: ubuntu-latest
    name: A job to update metadata and push a release to Zenodo

    steps:
      - name: Upload to Zenodo
        id: release
        uses: codingpaula/upload-to-zenodo@fix-octet-stream
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          zenodo_token: ${{ secrets.ZENODO_TOKEN }}
          zenodo_deposition_id: 13623775
          zenodo_publish: true
          commit_message: "Update CITATION.cff"
          citation_cff: true
