name: Test on Push

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  check:
    uses: ./.github/workflows/_check.yml

  test:
    uses: ./.github/workflows/_test.yml
    with:
      python-versions: '["3.9"]'
      scope: '["pytest"]'

  slack:
    needs: [check, test]
    uses: ./.github/workflows/_slack.yml
    with:
      workflow-name: "NiceGUI Push"
    secrets: inherit
