name: Test on Push

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  check:
    uses: ./.github/workflows/_check.yml

  test:
    uses: ./.github/workflows/_test.yml
    with:
      python-versions: '["3.9"]'
      scope: '["pytest"]'

  ci-gate:
    runs-on: ubuntu-latest
    needs: [check, test]
    steps:
      - run: echo "Gate passed"

  slack:
    needs: [check, test]
    uses: ./.github/workflows/_slack.yml
    with:
      workflow-name: "NiceGUI Push"
      needs-context: ${{ toJson(needs) }}
    secrets: inherit
